export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SINGLEPRODUCT = 'GET_SINGLE_PRODUCT';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const GET_MORE_PRODUCTS = 'GET_MORE_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART'